//import db from '../lib/database.js'
import { canLevelUp } from '../lib/levelling.js'

export async function before(m, { conn }) {
let user = global.db.data.users[m.sender]
let chat = global.db.data.chats[m.chat]
if (!chat.autolevelup) return !0
let before = user.level * 1
while (canLevelUp(user.level, user.exp, global.multiplier))
user.level++
user.role = global.rpg.role(user.level).name
if (before !== user.level) {
    
conn.reply(m.chat, [`*「 تهانينا على الترقية 🆙🥳 」*\n\nتهانينا لقد ارتقيت إلى مستوى جديد، استمر على هذا المنوال 👏\n\n*• المستوى:* ${before} ⟿ ${user.level}\n*• الرتبة:* ${user.role}\n\n_*لمعرفة نقاطك الحالية استخدم الأمر #level*_`, `@${m.sender.split`@`[0]} أوه! لقد وصلت إلى المستوى التالي\n*• المستوى:* ${before} ⟿ ${user.level}\n\n_*لمعرفة من هو في الصدارة استخدم الأمر #lb*_`, `ما شاء الله @${m.sender.split`@`[0]} لقد وصلت إلى مستوى جديد 🙌\n\n*• المستوى الجديد:* ${user.level}\n*• المستوى السابق:* ${before}\n`].getRandom(), m, {contextInfo: {externalAdReply :{ mediaUrl: null, mediaType: 1, description: null, title: wm, body: ' 💫 سوبر بوت واتساب 🥳 ', previewType: 0, thumbnail: img.getRandom(), sourceUrl: redes.getRandom()}}})
}}		

global.rpg = {
emoticon(string) {
string = string.toLowerCase()
let emot = { role: '🏅',
level: '⬆️'
}
let results = Object.keys(emot).map(v => [v, new RegExp(v, 'gi')]).filter(v => v[1].test(string))
if (!results.length) return ''
else return emot[results[0][0]]
}, 
role(level) {
level = parseInt(level)
if (isNaN(level)) return { name: '', level: '' }
    // this code make config.js to be a more understandable code
const role = [
  { name: 'مبتدئ(ة) V', level: 0 }, 
{ name: 'مبتدئ(ة) IV', level: 4 }, 
{ name: 'مبتدئ(ة) III', level: 8 }, 
{ name: 'مبتدئ(ة) II', level: 12 }, 
{ name: 'مبتدئ(ة) I', level: 16 },
{ name: 'متعلم(ة) V', level: 20 }, 
{ name: 'متعلم(ة) IV', level: 24 }, 
{ name: 'متعلم(ة) III', level: 28 }, 
{ name: 'متعلم(ة) II', level: 32 }, 
{ name: 'متعلم(ة) I', level: 36 },
{ name: 'مستكشف(ة) V', level: 40 }, 
{ name: 'مستكشف(ة) IV', level: 44 }, 
{ name: 'مستكشف(ة) III', level: 48 }, 
{ name: 'مستكشف(ة) II', level: 52 }, 
{ name: 'مستكشف(ة) I', level: 56 },
{ name: 'معلم(ة) V', level: 60 }, 
{ name: 'معلم(ة) IV', level: 64 }, 
{ name: 'معلم(ة) III', level: 68 }, 
{ name: 'معلم(ة) II', level: 72 }, 
{ name: 'معلم(ة) I', level: 76 },
{ name: 'حديد V', level: 80 }, 
{ name: 'حديد IV', level: 84 }, 
{ name: 'حديد III', level: 88 }, 
{ name: 'حديد II', level: 92 }, 
{ name: 'حديد I', level: 96 },
{ name: 'فضة V', level: 100 }, 
{ name: 'فضة IV', level: 104 }, 
{ name: 'فضة III', level: 108 }, 
{ name: 'فضة II', level: 112 }, 
{ name: 'فضة I', level: 116 },
{ name: 'ذهب V', level: 120 }, 
{ name: 'ذهب IV', level: 124 }, 
{ name: 'ذهب III', level: 128 }, 
{ name: 'ذهب II', level: 132 }, 
{ name: 'ذهب I', level: 136 },
{ name: 'بارد V', level: 140 }, 
{ name: 'بارد IV', level: 144 }, 
{ name: 'بارد III', level: 148 }, 
{ name: 'بارد II', level: 152 }, 
{ name: 'بارد I', level: 156 },
{ name: 'مستحضر الأرواح V', level: 160 }, 
{ name: 'مستحضر الأرواح IV', level: 164 }, 
{ name: 'مستحضر الأرواح III', level: 168 }, 
{ name: 'مستحضر الأرواح II', level: 172 }, 
{ name: 'مستحضر الأرواح I', level: 176 },
{ name: 'ساحر V', level: 180 }, 
{ name: 'ساحر IV', level: 184 }, 
{ name: 'ساحر III', level: 188 }, 
{ name: 'ساحر II', level: 192 }, 
{ name: 'ساحر I', level: 196 },
{ name: 'ساحر عظيم V', level: 200 }, 
{ name: 'ساحر عظيم IV', level: 204 }, 
{ name: 'ساحر عظيم III', level: 208 }, 
{ name: 'ساحر عظيم II', level: 212 }, 
{ name: 'ساحر عظيم I', level: 216 },
{ name: 'ساحر كبير V', level: 220 }, 
{ name: 'ساحر كبير IV', level: 224 }, 
{ name: 'ساحر كبير III', level: 228 }, 
{ name: 'ساحر كبير II', level: 232 }, 
{ name: 'ساحر كبير I', level: 236 },
{ name: 'عراف(ة) V', level: 240 }, 
{ name: 'عراف(ة) IV', level: 244 }, 
{ name: 'عراف(ة) III', level: 248 }, 
{ name: 'عراف(ة) II', level: 252 }, 
{ name: 'عراف(ة) I', level: 256 },
{ name: 'حكيم(ة) V', level: 260 }, 
{ name: 'حكيم(ة) IV', level: 264 }, 
{ name: 'حكيم(ة) III', level: 268 }, 
{ name: 'حكيم(ة) II', level: 272 }, 
{ name: 'حكيم(ة) I', level: 276 },
{ name: 'كاهن(ة) V', level: 280 }, 
{ name: 'كاهن(ة) IV', level: 284 }, 
{ name: 'كاهن(ة) III', level: 288 }, 
{ name: 'كاهن(ة) II', level: 292 }, 
{ name: 'كاهن(ة) I', level: 296 },
{ name: 'سارق(ة) V', level: 300 }, 
{ name: 'سارق(ة) IV', level: 304 }, 
{ name: 'سارق(ة) III', level: 308 }, 
{ name: 'سارق(ة) II', level: 312 }, 
{ name: 'سارق(ة) I', level: 316 },
{ name: 'مقاتل(ة) V', level: 320 }, 
{ name: 'مقاتل(ة) IV', level: 324 }, 
{ name: 'مقاتل(ة) III', level: 328 }, 
{ name: 'مقاتل(ة) II', level: 332 }, 
{ name: 'مقاتل(ة) I', level: 336 },
{ name: 'رامي(ة) V', level: 340 }, 
{ name: 'رامي(ة) IV', level: 344 }, 
{ name: 'رامي(ة) III', level: 348 }, 
{ name: 'رامي(ة) II', level: 352 }, 
{ name: 'رامي(ة) I', level: 356 },
{ name: 'قناص(ة) V', level: 360 }, 
{ name: 'قناص(ة) IV', level: 364 }, 
{ name: 'قناص(ة) III', level: 368 }, 
{ name: 'قناص(ة) II', level: 372 }, 
{ name: 'قناص(ة) I', level: 376 },
{ name: 'نينجا V', level: 380 }, 
{ name: 'نينجا IV', level: 384 }, 
{ name: 'نينجا III', level: 388 }, 
{ name: 'نينجا II', level: 392 }, 
{ name: 'نينجا I', level: 396 },
{ name: 'ساموراي V', level: 400 }, 
{ name: 'ساموراي IV', level: 404 }, 
{ name: 'ساموراي III', level: 408 }, 
{ name: 'ساموراي II', level: 412 }, 
{ name: 'ساموراي I', level: 416 },
{ name: 'محارب(ة) V', level: 420 }, 
{ name: 'محارب(ة) IV', level: 424 }, 
{ name: 'محارب(ة) III', level: 428 }, 
{ name: 'محارب(ة) II', level: 432 }, 
{ name: 'محارب(ة) I', level: 436 },
{ name: 'أسطورة V', level: 440 }, 
{ name: 'أسطورة IV', level: 444 }, 
{ name: 'أسطورة III', level: 448 }, 
{ name: 'أسطورة II', level: 452 }, 
{ name: 'أسطورة I', level: 456 },
{ name: 'بطل(ة) V', level: 460 }, 
{ name: 'بطل(ة) IV', level: 464 }, 
{ name: 'بطل(ة) III', level: 468 }, 
{ name: 'بطل(ة) II', level: 472 }, 
{ name: 'بطل(ة) I', level: 476 },
{ name: 'سيد(ة) عظيم(ة) V', level: 480 }, 
{ name: 'سيد(ة) عظيم(ة) IV', level: 484 }, 
{ name: 'سيد(ة) عظيم(ة) III', level: 488 }, 
{ name: 'سيد(ة) عظيم(ة) II', level: 492 }
, { name: 'سيد(ة) كبير(ة) I', level: 496 },
{ name: 'كبير(ة) V', level: 500 }, 
{ name: 'كبير(ة) IV', level: 504 }, 
{ name: 'كبير(ة) III', level: 508 }, 
{ name: 'كبير(ة) II', level: 512 }, 
{ name: 'كبير(ة) I', level: 516 },
{ name: 'خالد(ة) V', level: 520 }, 
{ name: 'خالد(ة) IV', level: 524 }, 
{ name: 'خالد(ة) III', level: 528 }, 
{ name: 'خالد(ة) II', level: 532 }, 
{ name: 'خالد(ة) I', level: 536 },
{ name: 'نيفالي V', level: 540 }, 
{ name: 'نيفالي IV', level: 544 }, 
{ name: 'نيفالي III', level: 548 }, 
{ name: 'نيفالي II', level: 552 }, 
{ name: 'نيفالي I', level: 556 },
{ name: 'أبدي(ة) V', level: 560 }, 
{ name: 'أبدي(ة) IV', level: 564 }, 
{ name: 'أبدي(ة) III', level: 568 }, 
{ name: 'أبدي(ة) II', level: 572 }, 
{ name: 'أبدي(ة) I', level: 576 },
{ name: 'نيبتون V', level: 580 }, 
{ name: 'نيبتون IV', level: 584 }, 
{ name: 'نيبتون III', level: 588 }, 
{ name: 'نيبتون II', level: 592 }, 
{ name: 'نيبتون I', level: 596 },
{ name: 'بلوتو V', level: 600 }, 
{ name: 'بلوتو IV', level: 604 }, 
{ name: 'بلوتو III', level: 608 }, 
{ name: 'بلوتو II', level: 612 }, 
{ name: 'بلوتو I', level: 616 },
{ name: 'إريس V', level: 620 }, 
{ name: 'إريس IV', level: 624 }, 
{ name: 'إريس III', level: 628 }, 
{ name: 'إريس II', level: 632 }, 
{ name: 'إريس I', level: 636 },
{ name: 'ارتقاء V', level: 640 }, 
{ name: 'ارتقاء IV', level: 644 }, 
{ name: 'ارتقاء III', level: 648 }, 
{ name: 'ارتقاء II', level: 652 }, 
{ name: 'ارتقاء I', level: 656 },
{ name: 'إليزيوم V', level: 660 }, 
{ name: 'إليزيوم IV', level: 664 }, 
{ name: 'إليزيوم III', level: 668 }, 
{ name: 'إليزيوم II', level: 672 }, 
{ name: 'إليزيوم I', level: 676 },
{ name: 'أثير V', level: 680 }, 
{ name: 'أثير IV', level: 684 }, 
{ name: 'أثير III', level: 688 }, 
{ name: 'أثير II', level: 692 }, 
{ name: 'أثير I', level: 696 },
{ name: 'غايا V', level: 700 }, 
{ name: 'غايا IV', level: 704 }, 
{ name: 'غايا III', level: 708 },
{ name: 'غايا II', level: 712 }, 
{ name: 'غايا I', level: 716 },
{ name: 'هاديس V', level: 720 },
{ name: 'هاديس IV', level: 724 }, 
{ name: 'هاديس III', level: 728 }, 
{ name: 'هاديس II', level: 732 }, 
{ name: 'هاديس I', level: 736 },
{ name: 'ديامانتي V', level: 740 },
{ name: 'ديامانتي IV', level: 744 }, 
{ name: 'ديامانتي III', level: 748 }, 
{ name: 'ديامانتي II', level: 752 }, 
{ name: 'ديامانتي I', level: 756 },
{ name: 'ديامانتي V', level: 760 }, 
{ name: 'ديامانتي IV', level: 764 }, 
{ name: 'ديامانتي III', level: 768 }, 
{ name: 'ديامانتي II', level: 772 }, 
{ name: 'ديامانتي I', level: 776 },
{ name: 'محترف في نوفابوت-MD V', level: 780 }, 
{ name: 'محترف في نوفابوت-MD IV', level: 784 }, 
{ name: 'محترف في نوفابوت-MD III', level: 788 }, 
{ name: 'محترف في نوفابوت-MD II', level: 792 }, 
{ name: 'محترف في نوفابوت-MD I', level: 796 },
{ name: 'محترف في نوفابوت-MD V', level: 800 }, 
{ name: 'محترف في نوفابوت-MD IV', level: 804 }, 
{ name: 'محترف في نوفابوت-MD III', level: 808 }, 
{ name: 'محترف في نوفابوت-MD II', level: 812 }, 
{ name: 'محترف في نوفابوت-MD I', level: 816 },
{ name: 'محترف كبير V', level: 820 }, 
{ name: 'محترف كبير IV', level: 824 }, 
{ name: 'محترف كبير III', level: 828 }, 
{ name: 'محترف كبير II', level: 832 }, 
{ name: 'محترف كبير I', level: 836 },
{ name: 'محترف كبير V', level: 840 }, 
{ name: 'محترف كبير IV', level: 844 }, 
{ name: 'محترف كبير III', level: 848 }, 
{ name: 'محترف كبير II', level: 852 }, 
{ name: 'محترف كبير I', level: 856 },
{ name: 'أسطوري(ة) V', level: 860 }, 
{ name: 'أسطوري(ة) IV', level: 864 }, 
{ name: 'أسطوري(ة) III', level: 868 }, 
{ name: 'أسطوري(ة) II', level: 872 }, 
{ name: 'أسطوري(ة) I', level: 876 },
{ name: 'نوفا V', level: 880 }, 
{ name: 'نوفا IV', level: 884 }, 
{ name: 'نوفا III', level: 888 }, 
{ name: 'نوفا II', level: 892 }, 
{ name: 'نوفا I', level: 896 },
{ name: 'أسطوري(ة) V', level: 900 }, 
{ name: 'أسطوري(ة) IV', level: 904 }, 
{ name: 'أسطوري(ة) III', level: 908 }, 
{ name: 'أسطوري(ة) II', level: 912 }, 
{ name: 'أسطوري(ة) I', level: 916 },
{ name: 'أسطورة V', level: 920 }, 
{ name: 'أسطورة IV', level: 924 }, 
{ name: 'أسطورة III', level: 928 }, 
{ name: 'أسطورة II', level: 932 }, 
{ name: 'أسطورة I', level: 936 },
{ name: 'أسطورة V', level: 940 }, 
{ name: 'أسطورة IV', level: 944 }, 
{ name: 'أسطورة III', level: 948 }, 
{ name: 'أسطورة II', level: 952 }, 
{ name: 'أسطورة I', level: 956 },
{ name: 'نجمي(ة) V', level: 960 }, 
{ name: 'نجمي(ة) IV', level: 964 }, 
{ name: 'نجمي(ة) III', level: 968 }, 
{ name: 'نجمي(ة) II', level: 972 }, 
{ name: 'نجمي(ة) I', level: 976 },
{ name: 'الصفوة العليا V', level: 980 }, 
{ name: 'الصفوة العليا IV', level: 984 }, 
{ name: 'الصفوة العليا III', level: 988 }, 
{ name: 'الصفوة العليا II', level: 992 }, 
{ name: 'الصفوة العليا I', level: 996 },
{ name: 'النخبة العالمية V', level: 1000 }, 
{ name: 'النخبة العالمية IV', level: 1004 }, 
{ name: 'النخبة العالمية III', level:1008}, 
{ name: 'النخبة العالمية II', level: 1012 }, 
{ name: 'النخبة العالمية I', level: 1016 },
{ name: 'النخبة العالمية V', level: 1020 }, 
{ name: 'النخبة العالمية IV', level: 1024 }, 
{ name: 'النخبة العالمية III', level: 1028 }, 
{ name: 'النخبة العالمية II', level: 1032 }, 
{ name: 'النخبة العالمية I', level: 1036 },
{ name: 'النخبة العالمية V', level: 1040 }, 
{ name: 'النخبة العالمية IV', level: 1044 }, 
{ name: 'النخبة العالمية III', level: 1048 }, 
{ name: 'النخبة العالمية II', level: 1052 }, 
{ name: 'النخبة العالمية I', level: 1056 },
{ name: 'النخبة العالمية V', level: 1060 }, 
{ name: 'النخبة العالمية IV', level: 1064 }, 
{ name: 'النخبة العالمية III', level: 1068 }, 
{ name: 'النخبة العالمية II', level: 1072 }, 
{ name: 'النخبة العالمية I', level: 1076 },
    ]

    return role.reverse().find(role => level >= role.level)
  }
}
